version: '3.8'

services:
  speech-to-text-api:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=production
      - PORT=5050
      - WHISPER_MODEL=base
      - MAX_CONCURRENT_JOBS=8
    env_file:
      - .env
    runtime: nvidia
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4.0'
        reservations:
          memory: 4G
          cpus: '2.0'
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./whisper_output:/app/whisper_output
      - ./config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - speech-to-text-api
    restart: unless-stopped
